In [26]:
%matplotlib inline
import sympy as sympy
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
from scipy import *

class LinearAlgebra:
    def operation_with_matric(self, op, a1, a2):
        if op == '+':
            return self.add_matrix(a1, a2)
        elif op == '-':
            return self.sub_matrix(a1, a2)
        elif op == '*':
            return self.mul_matrix(a1, a2)
        else:
            raise Exception(f"Operation {op} is not supported")    
        
    def operation_with_scaler(self, op, scaler, a2):
        if op == '+':
            return self.add_scaler_matrix(scaler, a2)
        elif op == '-':
            return self.sub_scaler_matrix(scaler, a2)
        elif op == '*':
            return self.mul_scaler_matrix(scaler, a2)     
        else:
            raise Exception(f"Operation {op} is not supported")

    def add_matrix(self, a1, a2):
        m1 = np.array(a1)
        m2 = np.array(a2)
        
        if m1.shape[0] == m2.shape[0] and m1.shape[1] == m2.shape[1]:
            return m1 + m2
        else:
            raise Exception(f"Addion of two different size matrics not allowed")

    def mul_matrix(self, a1, a2):
        m1 = np.array(a1)
        m2 = np.array(a2)
        
        if m1.shape[1] == m2.shape[0]:
            return np.matmul(m1, m2)
        else:
            raise Exception(f"Multiply of two matrics with different columns and rows size respectively not allowed")

    def sub_matrix(self, a1, a2):
        m1 = np.array(a1)
        m2 = np.array(a2)
        
        if m1.shape[0] == m2.shape[0] and m1.shape[1] == m2.shape[1]:
            return m1 - m2
        else:
            raise Exception(f"Subtraction of two different size matrics not allowed")
    
    
    def add_scaler_matrix(self, scaler, array):
        matrix = np.array(array)
        return matrix + scaler
    
    def sub_scaler_matrix(self, scaler, array):
        matrix = np.array(array)
        return matrix - scaler
        
    def mul_scaler_matrix(self, scaler, array):
        matrix = np.array(array)
        return matrix * scaler        

if __name__ == '__main__':
    la = LinearAlgebra()
    A = [[1, 2], [3, 4]]
    print(f'A + 3 = {A} + 3 = \n')
    print(la.operation_with_scaler('+', 3, A))
    
    print('\n')
    print(f'A - 3 = {A} - 3 = \n')
    print(la.operation_with_scaler('-', 3, A))

    print('\n')
    print(f'A x 3 = {A} x 3 = \n')
    print(la.operation_with_scaler('*', 3, A))

    B = [[5, 6], [7, 8]]
    print('\n')
    print(f'A + B = {A} + {B} = \n')
    print(la.operation_with_matric('+', A, B))
    print('\n')
    print(f'A - B = {A} - {B} = \n')
    print(la.operation_with_matric('-', A, B))
    print('\n')
    print(f'A x B = {A} x {B} = \n')
    print(la.operation_with_matric('*', A, B))

    C = [[1, 2]]
    
    print('\n')
    print(f'A x C = {A} x {C} = \n')
    print(la.operation_with_matric('*', A, C))

A + 3 = [[1, 2], [3, 4]] + 3 = 

[[4 5]
 [6 7]]


A - 3 = [[1, 2], [3, 4]] - 3 = 

[[-2 -1]
 [ 0  1]]


A x 3 = [[1, 2], [3, 4]] x 3 = 

[[ 3  6]
 [ 9 12]]


A + B = [[1, 2], [3, 4]] + [[5, 6], [7, 8]] = 

[[ 6  8]
 [10 12]]


A - B = [[1, 2], [3, 4]] - [[5, 6], [7, 8]] = 

[[-4 -4]
 [-4 -4]]


A x B = [[1, 2], [3, 4]] x [[5, 6], [7, 8]] = 

(2, 2)
(2, 2)
[[19 22]
 [43 50]]


A x C = [[1, 2], [3, 4]] x [[1, 2]] = 

(2, 2)
(1, 2)


Exception: Multiply of two matrics with different columns and rows size respectively not allowed