In [14]:
%matplotlib inline
import sympy as sympy
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
from scipy import *

class LinearAlgebra:
    def operation_with_matrix()
    def operation_with_scaler(self, op, a1, a2):
        if op == '+':
            return self.add_scaler_matrix(a1, a2)
        elif op == '-':
            return self.sub_scaler_matrix(a1, a2)
        elif op == '*':
            return self.mul_scaler_matrix(a1, a2)     
        else:
            raise Exception(f"Operation {op} is not supported")
            
    def add_scaler_matrix(self, scaler, array):
        matrix = np.array(array)
        return matrix + scaler
    
    def sub_scaler_matrix(self, scaler, array):
        matrix = np.array(array)
        return matrix - scaler
        
    def mul_scaler_matrix(self, scaler, array):
        matrix = np.array(array)
        return matrix * scaler        

if __name__ == '__main__':
    la = LinearAlgebra()
    A = [[5, 1], [6, 2]]
    print(f'A + 3 = {A} + 3 = \n')
    print(la.operation_with_scaler('+', 3, A))
    
    print('\n')
    print(f'A + 3 = {A} - 3 = \n')
    print(la.operation_with_scaler('-', 3, A))

    print('\n')
    print(f'A + 3 = {A} x 3 = \n')
    print(la.operation_with_scaler('*', 3, A))

A + 3 = [[5, 1], [6, 2]] + 3 = 

[[8 4]
 [9 5]]


A + 3 = [[5, 1], [6, 2]] - 3 = 

[[ 2 -2]
 [ 3 -1]]


A + 3 = [[5, 1], [6, 2]] x 3 = 

[[15  3]
 [18  6]]
